// Joke API configuration
const defaultSettings = {
    apiUrl: 'https://v2.jokeapi.dev/joke',
    cacheLimit: 20,
    autoPlay: false,
    delay: 0,
    primaryColor: '#66fcf1',
    accentColor: '#39ff14'
};

let settings = { ...defaultSettings };
let currentJoke = null;
let jokesLoaded = 0;
let favorites = [];
let jokeCache = [];

// Initialize
window.addEventListener('DOMContentLoaded', function() {
    loadSettings();
    loadFavorites();
    getRandomJoke();
    updateStats();
});

// Fetch random joke from API
async function getRandomJoke() {
    const category = document.getElementById('joke-category').value;
    const type = document.getElementById('joke-type').value;
    const safeMode = document.getElementById('safe-mode').checked;
    
    const loading = document.getElementById('loadingSpinner');
    const content = document.getElementById('jokeContent');
    
    loading.style.display = 'flex';
    content.style.display = 'none';
    
    try {
        // Build API URL
        let url = settings.apiUrl;
        
        // Add category
        if (category !== 'any') {
            url += '/' + category;
        } else {
            url += '/Any';
        }
        
        // Add parameters
        const params = new URLSearchParams();
        if (type !== 'any') params.append('type', type);
        if (safeMode) params.append('safe-mode');
        
        if (params.toString()) {
            url += '?' + params.toString();
        }
        
        const response = await fetch(url);
        
        if (!response.ok) throw new Error('Failed to fetch joke');
        
        const data = await response.json();
        
        if (data.error) {
            throw new Error('No jokes found in this category');
        }
        
        currentJoke = data;
        jokesLoaded++;
        jokeCache.push(data);
        
        // Limit cache size
        if (jokeCache.length > settings.cacheLimit) {
            jokeCache.shift();
        }
        
        displayJoke(data);
        updateStats();
        
    } catch (error) {
        console.error('Error fetching joke:', error);
        document.getElementById('jokeText').textContent = `❌ Error: ${error.message}`;
        document.getElementById('jokeAnswer').style.display = 'none';
    } finally {
        loading.style.display = 'none';
        content.style.display = 'block';
    }
}

// Display joke
function displayJoke(joke) {
    const jokeText = document.getElementById('jokeText');
    const jokeAnswer = document.getElementById('jokeAnswer');
    
    if (joke.type === 'twopart') {
        jokeText.textContent = joke.setup;
        jokeAnswer.textContent = joke.delivery;
        jokeAnswer.style.display = 'block';
    } else {
        jokeText.textContent = joke.joke;
        jokeAnswer.style.display = 'none';
    }
    
    // Update favorite button
    updateFavoriteButton();
}

// Share joke
function shareJoke() {
    if (!currentJoke) {
        alert('No joke to share!');
        return;
    }
    
    let jokeText = currentJoke.type === 'twopart' 
        ? `${currentJoke.setup}\n${currentJoke.delivery}` 
        : currentJoke.joke;
    
    // Add text to clipboard
    const text = `😂 ${jokeText}\n\nGenerated by Random Joke Generator`;
    
    navigator.clipboard.writeText(text).then(() => {
        alert('✓ Joke copied to clipboard!');
    }).catch(() => {
        // Fallback for older browsers
        const textarea = document.createElement('textarea');
        textarea.value = text;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        alert('✓ Joke copied to clipboard!');
    });
}

// Toggle favorite
function toggleFavorite() {
    if (!currentJoke) return;
    
    const index = favorites.findIndex(j => 
        (j.joke === currentJoke.joke || j.setup === currentJoke.setup) &&
        j.type === currentJoke.type
    );
    
    if (index > -1) {
        favorites.splice(index, 1);
    } else {
        favorites.push(currentJoke);
    }
    
    saveFavorites();
    updateFavoriteButton();
    displayFavorites();
    updateStats();
}

// Update favorite button styling
function updateFavoriteButton() {
    if (!currentJoke) return;
    
    const isFavorite = favorites.some(j => 
        (j.joke === currentJoke.joke || j.setup === currentJoke.setup) &&
        j.type === currentJoke.type
    );
    
    const btn = document.querySelector('.btn-favorite');
    if (isFavorite) {
        btn.style.opacity = '1';
        btn.textContent = '❤️ Favorited';
    } else {
        btn.style.opacity = '0.7';
        btn.textContent = '🤍 Favorite';
    }
}

// Display favorites
function displayFavorites() {
    const container = document.getElementById('favoritesList');
    
    if (favorites.length === 0) {
        container.innerHTML = '<p style="text-align: center; color: #aaa;">No favorites yet. Click the heart button to save jokes!</p>';
        return;
    }
    
    container.innerHTML = favorites.map((joke, index) => `
        <div class="favorite-item">
            <div class="favorite-text">
                ${joke.type === 'twopart' 
                    ? `<strong>${joke.setup}</strong><br><em>${joke.delivery}</em>` 
                    : joke.joke
                }
            </div>
            <button class="favorite-remove" onclick="removeFavorite(${index})">Remove</button>
        </div>
    `).join('');
}

// Remove favorite
function removeFavorite(index) {
    favorites.splice(index, 1);
    saveFavorites();
    displayFavorites();
    updateStats();
    if (currentJoke) updateFavoriteButton();
}

// Clear all favorites
function clearFavorites() {
    if (confirm('Are you sure you want to clear all favorites?')) {
        favorites = [];
        saveFavorites();
        displayFavorites();
        updateStats();
        if (currentJoke) updateFavoriteButton();
    }
}

// Update stats
function updateStats() {
    document.getElementById('jokesLoaded').textContent = jokesLoaded;
    document.getElementById('favoritesCount').textContent = favorites.length;
}

// Update joke type filter
function updateJokeType() {
    getRandomJoke();
}

// Toggle admin panel
function toggleAdminPanel() {
    const panel = document.getElementById('adminPanel');
    panel.style.display = panel.style.display === 'block' ? 'none' : 'block';
}

// Apply custom theme
function applyCustomTheme() {
    const primary = document.getElementById('primary-color').value;
    const accent = document.getElementById('accent-color').value;
    
    document.documentElement.style.setProperty('--primary-color', primary);
    document.documentElement.style.setProperty('--accent-color', accent);
}

// Save settings
function saveSettings() {
    settings.apiUrl = document.getElementById('api-url').value;
    settings.cacheLimit = parseInt(document.getElementById('cache-limit').value);
    settings.autoPlay = document.getElementById('auto-play').checked;
    settings.delay = parseInt(document.getElementById('delay').value);
    settings.primaryColor = document.getElementById('primary-color').value;
    settings.accentColor = document.getElementById('accent-color').value;
    
    localStorage.setItem('jokeSettings', JSON.stringify(settings));
    applyCustomTheme();
    alert('✓ Settings saved!');
}

// Load settings
function loadSettings() {
    const saved = localStorage.getItem('jokeSettings');
    if (saved) {
        settings = { ...defaultSettings, ...JSON.parse(saved) };
    }
    
    document.getElementById('api-url').value = settings.apiUrl;
    document.getElementById('cache-limit').value = settings.cacheLimit;
    document.getElementById('auto-play').checked = settings.autoPlay;
    document.getElementById('delay').value = settings.delay;
    document.getElementById('primary-color').value = settings.primaryColor;
    document.getElementById('accent-color').value = settings.accentColor;
    
    applyCustomTheme();
}

// Reset settings
function resetSettings() {
    if (confirm('Reset all settings to default?')) {
        settings = { ...defaultSettings };
        localStorage.removeItem('jokeSettings');
        loadSettings();
        alert('✓ Settings reset to default!');
    }
}

// Save favorites
function saveFavorites() {
    localStorage.setItem('jokesFavorites', JSON.stringify(favorites));
}

// Load favorites
function loadFavorites() {
    const saved = localStorage.getItem('jokesFavorites');
    if (saved) {
        favorites = JSON.parse(saved);
        displayFavorites();
    }
}